### ISSUE TITLE
🐞 Documentation Bug: no entry publication date in changelog RSS feed

### ISSUE THREAD

**Issue by rclement** [scaleway/docs-content#1035]
### What content on scaleway.com/en/docs is affected?

https://www.scaleway.com/en/docs/changelog/rss.xml

### What part(s) of the content would you like to see updated?

The generated RSS feed for the [Changelog](https://www.scaleway.com/en/docs/changelog/) page is missing publication dates for entries.

**Cause**: `item` elements are all missing a `pubDate` attribute.

**Consequence**: when importing the feed into a reader, history is lost as there is no dates provided, and all sorts of deduplication issues appear.

_Reference_: https://www.rssboard.org/rss-specification#ltpubdategtSubelementOfLtitemgt

**Comment by tthsympa** [comment]
Hey! Thanks for filling an issue for our Documentation!

Can you add a screenshot of "and all sorts of deduplication issues appear."? Will be easier for us to debug.

We will take a look!

**Comment by rclement** [comment]
Here is a screenshot of the feed when importing it into Miniflux (a great OSS feed reader), where articles cannot be sorted in order because there is no date (and by default it assumes the feed importation date thus the "yesterday" mention):

<img width="760" alt="Screenshot 2022-11-23 at 17 22 48" src="https://user-images.githubusercontent.com/1238873/203598022-ef982c4f-cba6-4ea9-b15c-ad24295642f0.png">

Here is a screenshot of the missing, `<pubDate>` element on all `<item>` elements:

<img width="895" alt="Screenshot 2022-11-23 at 17 21 07" src="https://user-images.githubusercontent.com/1238873/203597627-8d9b533b-db14-46e8-99d5-b303b5551927.png">

**Comment by tthsympa** [comment]
Yep, we indeed indicate the `pubDate` field during generation, but strangely it is not present in the final XML

**Comment by tthsympa** [comment]
Found why! Will make a PR on our side, I will ping you when it's live 🙂

**Comment by tthsympa** [comment]
Hey @rclement it's released on our side! I suggest that you delete the feed on your reader and at it again
Please tell me if this correct it on your side :)

Here's a screenshot taken from my reader (Feedbro):
<img width="300" alt="Screenshot 2022-11-24 at 13 31 09" src="https://user-images.githubusercontent.com/9251679/203785436-6eeea533-1811-446e-a915-23ce1434d26f.png">

**Comment by rclement** [comment]
@tthsympa Thanks for the heads-up!

Indeed, the entries do have a publication date now, so this is fixed as far as I can tell.
Here is a screenshot of the feed using Miniflux:

<img width="761" alt="Screenshot 2022-11-24 at 13 47 15" src="https://user-images.githubusercontent.com/1238873/203788485-1f16dadb-9b5d-4d5e-9df4-a6024e1ed359.png">

**Comment by tthsympa** [comment]
Sweet! I'm closing the issue, thanks!
