### ISSUE TITLE
[👩‍💻 Documentation Request]: Manage Zigbee connected devices with Scaleway IoT Hub and Observability

### ISSUE THREAD

**Issue by arthur-mrz** [scaleway/docs-content#1108]
### Summary

The documentation is for installing and configuring [Zigbee2mqtt ](https://www.zigbee2mqtt.io/) with IoT Hub. The tutorial will also develop a simple use case related to visualization with Observability. If successful, the first tutorial would be extended to document use cases leveraging other Scaleway products.

### Why is it needed?

Some people would like to have full control over the management of their connected devices which are used to monitor and control their environment. Zigbee 3.0 is one of the recognized technologies used for communication between these devices, but proprietary gateways are often required to interact with such a network. Open source software and managed services from trusted providers could be used instead to ensure an appropriate level of security and performance.

### Want to write this documentation yourself?

Yes

### Related PR(s)

#1120 

### (Optional) Scaleway Organization ID

e52e3a61-6e5f-4ba6-babf-0fe4500d1f32

**Comment by ofranc** [comment]
Hey @arthur-mrz ! Thanks for your message. Feel free to open a PR anytime to benefit from the 200e discount on your invoice.

**Comment by bene2k1** [comment]
Hello @arthur-mrz,

Thank you for your contribution to Scalway's Product Documentation. We have approved your content, which will be merged and released on our website next week. 

We have credited your account with a 200 € voucher, valid for six months, to say thank you for your work. 

Benedikt
