### ISSUE TITLE
[👩‍💻 Documentation Request]: Scaleway for Blockchains | Stateless Networks

### ISSUE THREAD

**Issue by zdanl** [scaleway/docs-content#1224]
### Summary

- serverless is generally regarded to as the jump before smartcontracts in evm (ethereum) blockchains
- scaleway seems to be working hard on mimicking blockchains as per serverless functions with inter-node messaging
- amazon aws is trying to get into the blockchain game as well, yet, isn't being very creative in doing so
- so far, the deployment time and real world use cases for blockchains/serverless on scaleway are limited
- web3 in general federates a great way for small businesses and upcoming startups to monetize on anything using crypto
- there might be value in a Wiki / Documentation Hub to collect use-cases, code, and an outlook

### Why is it needed?

- a compelling english wiki / bunch of documentation sites to explain why scaleway indeed does support the web3
- a critical commentary comparing serverless to blockchains
- a compelling write-up on what web3 compared to web2 really means and how in the light of gas fees on ethereum, scaleway is a proper alternative

### Want to write this documentation yourself?

Yes

### Related PR(s)

https://github.com/scaleway/serverless-examples/pull/10

### (Optional) Scaleway Organization ID

79eecd06-ae47-404c-bd9a-d793e62c06e1 

### Email address

dan@danzulla.com

**Comment by ofranc** [comment]
Hello @zdanl, thank you for your feedback and willingness to share your expertise. Your request sounds more like a blog post than a tutorial and therefore would not be qualified for the 200 euros voucher, unfortunately. Thanks again for getting in touch.
