### ISSUE TITLE
[👩‍💻 Documentation Request]: Tutorial to configure ingress-nginx proxy-protocol-v2 support

### ISSUE THREAD

**Issue by Grraahaam** [scaleway/docs-content#1231]
### Summary

This documentation is about configuring the `ingress-nginx ` to accept `proxy-protocol-v2` communication, here's the Slack threads about it : 
- https://scaleway-community.slack.com/archives/CD9JPK4KF/p1674483432890869
- https://scaleway-community.slack.com/archives/CD9JPK4KF/p1665128165284669

### Why is it needed?

Tutorial to setup the `ingress-nginx` to accept `proxy-protocol-v2` communication

### Want to write this documentation yourself?

Yes

### Related PR(s)

https://github.com/scaleway/docs-content/pull/1232

### (Optional) Scaleway Organization ID

You can send me a message on Slack, I'll send you my org-id if needed

### Email address

**@Grraahaam** (Slack - Scaleway Community)

**Comment by bene2k1** [comment]
Hello @Grraahaam,

Thank you for your contribution to our Product Documentation. Your PR has been merged and we have credited your account with a cloud credit for your contribution :) 

Benedikt
