### ISSUE TITLE
🐞 Documentation Bug: Curl sample for getting container logs does not work.

### ISSUE THREAD

**Issue by youpsla** [scaleway/docs-content#1341]
### What content on scaleway.com/en/docs is affected?

https://developers.scaleway.com/en/products/containers/api/#get-your-containers-logs

### What part(s) of the content would you like to see updated?

THe sample to retrieve container logs does not work:
```
curl -X GET -H "X-Auth-Token: $TOKEN" "https://api.scaleway.com/containers/v1beta1/regions/$REGION/logs?container_id=$CONTAINER_ID"

```

Instead using
```
curl -X GET -H "X-Auth-Token:  $TOKEN" "https://api.scaleway.com/containers/v1beta1/regions/$REGION/containers/$CONTAINER_ID/logs"
```
works fine

**Comment by bene2k1** [comment]
Hello @youpsla, 

Thank you for spotting this. We have updated the documentation and will deploy it asap. 

Benedikt
