### ISSUE TITLE
🐞 Documentation Bug: 

### ISSUE THREAD

**Issue by srounet** [scaleway/docs-content#1482]
### What content on scaleway.com/en/docs is affected?

https://www.scaleway.com/en/docs/tutorials/setup-postfix-ubuntu-bionic/

### What part(s) of the content would you like to see updated?

There is a typo within Sieve configuration at step 8 of the process. The targeted filepath is wrong, it should be changed.

```
7.
Create a global sieve filter in the file /var/vmail/mail/sieve/global/spam-global.sieve. It will move emails marked as spam directly to the spam folder:
...

8. Create a script, named /var/vmail/mail/sieve/global/spam-global.sieve, that will be triggered each time you manually move an email into the spam folder:
...

sievec /var/vmail/mail/sieve/global/spam-global.sieve
sievec /var/vmail/mail/sieve/global/report-spam.sieve   <<<<<<<
sievec /var/vmail/mail/sieve/global/report-ham.sieve
chown -R vmail: /var/vmail/mail/sieve/
```

# what need to change:

- The filepath of step 8 should be changed to `/var/vmail/mail/sieve/global/report-spam.sieve`.
- At the end of step 5, there should be a line indicating to `service dovecot restart`.
  - This is required otherwise the required configurations and plugins won't exists when executing `sievec` at step 10

**Comment by bene2k1** [comment]
Hello @srounet, 

Thank you for reporting this issue. I made a PR to fix the tutorial. You can see it here: https://github.com/scaleway/docs-content/pull/1545

Benedikt
