### ISSUE TITLE
👩‍💻 Documentation Request: aws-cli accessing object storage via k8s cluster

### ISSUE THREAD

**Issue by codezart** [scaleway/docs-content#1661]
### Summary

https://www.scaleway.com/en/docs/storage/object/api-cli/object-storage-aws-cli/#how-to-install-the-aws-cli

In the above docs link you've provided a way to access the s3 bucket. I've tried this and it works.

But when I do something similar for creating a container job that does `ls` it either gives me

```
An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: The AWS Access Key Id you provided does not exist in our records.
```

or 

```
Unable to locate credentials. You can configure credentials by running "aws configure".
```
I am using k8s python api to create the container this is the code I've implemented.
```
					client.V1Container(
						name="scaleway-cli",
						image="amazon/aws-cli:latest",
						command=['bash','-c'],
						args=[
							"aws configure set plugins.endpoint awscli_plugin_endpoint && " +
							"aws configure set s3.endpoint_url https://s3.fr-par.scw.cloud && " +
							"aws configure set signature_version s3v4 && " +
							"aws s3 ls && " +
							f"aws s3 cp s3://myobjectstore-files/myfile.sql  ."

						],
						env=[
							client.V1EnvVar(
								name="aws_access_key_id",
								value_from=client.V1EnvVarSource(
									secret_key_ref=client.V1SecretKeySelector(
										name="scaleway-s3-secret",
										key="accesskey"
									)
								)
							),
							client.V1EnvVar(
								name="aws_secret_access_key",
								value_from=client.V1EnvVarSource(
									secret_key_ref=client.V1SecretKeySelector(
										name="scaleway-s3-secret",
										key="secretkey"
									)
								)
							)
                        ],
					)

```
Therefore can you provide an example of a pod with a container that uses the amazon/aws-cli:latest image to do `ls` or `cp`.

### Why is it needed?

I have to do a job that copies some files from object storage to my k8s container.

Adding k8s integration to this would make life easier.

### Want to write this documentation yourself?

Yes

### Email address

codezart.git@gmail.com

**Comment by ldecarvalho-doc** [comment]
Hello,

Thank you for creating an issue.
However, I do not understand, do you wish to write this documentation yourself, or are you requesting an edit?
Thank you.

**Comment by codezart** [comment]
I would prefer writing the documentation myself but I believe there are some things I am not familiar with when using the packages. 

Therefore, I'm requesting an investigation to make this work for the use case provided in the issue's description. I've tried doing this using the documentation and other resources available online but I believe this requires unique configurations to make it work and require your assistance in making this work.

**Comment by ldecarvalho-doc** [comment]
Hello, 
Thanks for clarifying and sorry for the delay :slightly_smiling_face: 
After investigating the issue with the team, it seems that you are using AWS' official image, which does not include the `awscli-plugin-endpoint`. This means you are being directed to AWS instead of Scaleway.

Can you test the tutorial again, making sure you run `pip3 install aws-cli-plugin-endpoint`, found in step 1?

Thank you!

**Comment by ldecarvalho-doc** [comment]
Hello, 
Since we haven't had a recent response, we will be closing this issue. Feel free to open a new one or contact us on content@scaleway.com if you face further issues. Thank you.
