### ISSUE TITLE
👩‍💻 Documentation Request: Deploy Laravel to Scaleway Serverless Container

### ISSUE THREAD

**Issue by arthur-mrz** [scaleway/docs-content#1681]
### Summary

This tutorial provides a step-by-step guide for deploying a containerized Laravel application on the Scaleway cloud platform. It covers the entire process, from setting up the required infrastructure to deploying and running the application using Docker and Scaleway services (i.e., Serverless Containers). The tutorial aims to help developers easily deploy their Laravel applications on Scaleway by providing clear instructions and best practices.

Overview:
- Briefly explain what Scaleway is and its key features that make it suitable for deploying containerized applications
- Setting up a Scaleway services (Serverless Containers)
- Building the Laravel Docker Image
- Deploying the application
- Monitoring tools and techniques to monitor the deployed Laravel application

### Why is it needed?

This documentation is needed to facilitate the deployment of Laravel applications on the Scaleway cloud platform. By providing a detailed tutorial, developers can leverage containerization and Scaleway's infrastructure to deploy their applications quickly and efficiently. The tutorial covers essential topics, including infrastructure setup, containerization, deployment processes, etc. By following this guide, developers can save time and effort and ensure a smooth deployment experience for their Laravel applications on Scaleway.

### Want to write this documentation yourself?

Yes

### Related PR(s)

#1754

### (Optional) Scaleway Organization ID

e52e3a61-6e5f-4ba6-babf-0fe4500d1f32

**Comment by ofranc** [comment]
Hello @arthur-mrz, 

Thank you for your request. Be sure to add the link to your PR in this issue when it's ready.

Have a nice day and thank you for contributing 👋🏻

**Comment by ofranc** [comment]
Hey @arthur-mrz we just credited your account with a 200e voucher! Make sure to commit our suggestions so that we can merge and approve your PR asap! Thanks for contributing to Scaleway Documentation.
