### ISSUE TITLE
👩‍💻 Documentation Request: Details about the possible "variables" includable in IoT Hub Routes config

### ISSUE THREAD

**Issue by SebUndefined** [scaleway/docs-content#1775]
### Summary

In the documentation, some part mentions that we can include some variables in the IoT hub route configuration Such as [here](https://github.com/scaleway/docs-content/blob/17ff53eb5042e011d9c3a9eced29ec05c5e3bfbb/managed-services/iot-hub/api-cli/iot-hub-routes.mdx?plain=1#L96).  

"As we are not limited to binary payloads, in this example we will use MySQL functions to manipulate **$TOPIC** and **$PAYLOAD** placeholders."

### Why is it needed?

It would be great to details all the available variables. For example if '$DEVICEID' is available or not as their type. 
I would love to write the doc myself but I do not know the missing variables. 

### Want to write this documentation yourself?

No

**Comment by farhakennar** [comment]
Hello @SebUndefined ! Your issue has been reported and the only available variables for a Database route are indeed $TOPIC and $PAYLOAD. We will update the documentation to make it more clear. Thanks for notifying us 😊
