### ISSUE TITLE
[👩‍💻 Documentation Request]: Exposing services in Scaleway Kubernetes is only for TCP/HTTP

### ISSUE THREAD

**Issue by acdn-ndostert** [scaleway/docs-content#1903]
### Summary

In the page https://www.scaleway.com/en/docs/containers/kubernetes/api-cli/exposing-services/ it is not clear that we cannot expose UDP services, only TCP and HTTP.

On https://www.scaleway.com/en/docs/network/load-balancer/quickstart/ we see that

> Available protocols are HTTP or TCP.

### Why is it needed?

It would avoid unnecessary research for a feature that does not exist.

### Want to write this documentation yourself?

Yes

### Related PR(s)

https://github.com/scaleway/docs-content/pull/1902

### (Optional) Scaleway Organization ID

39926239-b22b-4d3e-b92a-9a0d16bb6c5d

**Comment by farhakennar** [comment]
Hey @acdn-ndostert, great point! Your PR has been merged and the doc website will soon be updated with your changes. Thanks for contributing to Scaleway's Product Documentation 😊
