### ISSUE TITLE
🐞 Documentation Bug: missing host in api call

### ISSUE THREAD

**Issue by alter-s** [scaleway/docs-content#1918]
### What content on scaleway.com/en/docs is affected?

https://www.scaleway.com/en/developers/api/kubernetes/

### What part(s) of the content would you like to see updated?

Step 5, the curl api call is obv. missing the host part (https://api.scaleway.com)

**Comment by bene2k1** [comment]
Hello @alter-s, 

well spotted. I am going to update the documentation. 
Thank you for your feedback. 

Benedikt
