### ISSUE TITLE
[👩‍💻 Documentation Request]: Make systemd-networkd the default DHCPv6 client for Dedibox-network

### ISSUE THREAD

**Issue by HLFH** [scaleway/docs-content#1920]
### Summary

The documentation needs a consequent update.

Which I have done here: https://github.com/scaleway/docs-content/pull/1919

### Why is it needed?

I think Scaleway should no longer recommend `dhclient` as default DHCPv6 client for the Dedibox network.
`dhclient` has reached EOL in 2022 and is discontinued. It creates a security risk for Scaleway users.

Scaleway should recommend `systemd-networkd` as default network manager and DHCPv4/DHCPv6 client for the Dedibox network. `systemd` is also natively installed on the [Dedibox operating systems](https://www.scaleway.com/en/dedibox/operating-systems/).

### Want to write this documentation yourself?

Yes

### Related PR(s)

https://github.com/scaleway/docs-content/pull/1919

### (Optional) Scaleway Organization ID
Not sure if this is an Organization ID?
Devopsy – gaspard@dhautefeuille.eu

### Email address

gaspard@dhautefeuille.eu

**Comment by Shot2** [comment]
"Scaleway should not recommend systemd-networkd because **it is buggy with DHCPv6 and the Dedibox network**."

It is likely worth mentioning which version(s) of systemd-networkd such a blanket statement refers to.

**Comment by HLFH** [comment]
@Shot2 

I am using the latest one available.

```
systemctl --version
systemd 253 (253.6-2-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
```

If you really think it is no longer buggy, feel free to submit a PR to update the tutorial with a complete configuration for `systemd-networkd`.
I'll be happy to try it out.

**Comment by HLFH** [comment]
@Shot2 Ok my comment about `systemd-networkd` is no longer valid. I managed to make it work. I will revamp the PR in favour of `systemd-networkd`.

**Comment by bene2k1** [comment]
Hello @HLFH 👋 

Thank you for your contribution to the Scaleway Product Documentation. Your PR has been approved and merged. The changes will be visible on the documentation website very soon. 

To thank you for your contribution I provided a 100€ cloud credit to your Scaleway account, valid for three months.

Benedikt
