### ISSUE TITLE
🐞 Documentation Bug: Install scaleway-ecosystem on RedHat-based distributions

### ISSUE THREAD

**Issue by boomaker** [scaleway/docs-content#1949]
### What content on scaleway.com/en/docs is affected?

https://www.scaleway.com/en/docs/network/vpc/troubleshooting/autoconfig-not-working/

### What part(s) of the content would you like to see updated?

It is suggested to use the following install command to install scaleway-ecosystem on RedHat-based distributions:

`# rpm -vUh https://github.com/scaleway/scaleway-packages/releases/download/v0.0.4/scaleway-ecosystem-0.0.5.noarch.rpm`

However, the version in this repository is not up-to-date (see: https://github.com/scaleway/scaleway-packages/releases), not to say it's very old (2021).

I guess it would be better to give a procedure to install scaleway-ecosystem through yum (and 0.0.6 is available on Scaleway yum repo), that will moreover facilitate future upgrades of the package.

**Comment by ldecarvalho-doc** [comment]
Hello @boomaker,
Thank you for bringing this to our attention. We will look into updating the troubleshoot and get back to you as soon as possible.
Have a nice day!

**Comment by bene2k1** [comment]
Hello @boomaker, 

We have updated the documentation https://github.com/scaleway/docs-content/pull/1965 and the content will be available on the documentation website with the next deployment of it.

Have a nice day.

Benedikt
