### ISSUE TITLE
👩‍💻 Documentation Request: 

### ISSUE THREAD

**Issue by ckdarby** [scaleway/docs-content#1964]
### Summary

Add documentation around how the Kosmos node-agent works.

### Why is it needed?

It is difficult to know how the node-agent works, and I could not find it on Scaleway's Github.

An example, does the node-agent establish connectivity outbound to the control plane or does the control plane require inbound access to the node in the pool?

### Want to write this documentation yourself?

No

**Comment by bene2k1** [comment]
Hello @ckdarby,

Thank you for contacting us about the Scaleway Kapsule `node-agent`. We acknowledge your interest in learning more about the tool. However, please understand that it is currently proprietary software, and we cannot disclose full implementation details at this time.

As you might have noticed, the tool establishes a connection to the control plane of your cluster, this connection is solely used for managing your cluster (e.g. migrating nodes to Private Network). No other data apart from cluster-related information is exchanged through this connection. Rest assured that your cluster's security and data privacy remain our utmost priority.

Benedikt
