### ISSUE TITLE
[👩‍💻 Documentation Request]: Deploying Minecraft Servers with Pterodactyl

### ISSUE THREAD

**Issue by TheTwoBoom** [scaleway/docs-content#2038]
### Summary

Deploying Minecraft Servers with Pterodactyl
Learn how to set up, manage, and optimize Minecraft servers using Pterodactyl control panel.

- Pterodactyl Introduction
- Setting Up Pterodactyl
- Creating Servers
- Configuring Minecraft Settings

### Why is it needed?

Pterodactyl is one of the most popular game server managment panels in the community, and it's often used for hosting minecraft servers. I think it's inportant to have documentation about it, because the "Creating your own Minecraft server" Tutorial is not suitable for production use if your hosting a whole Minecraft Network on a single Dedibox/Elastic Metal/Instance

### Want to write this documentation yourself?

Yes

**Comment by farhakennar** [comment]
Hello @TheTwoBoom,

Feel free to open a PR and take on the exciting challenge of writing documentation for us! We'll happily review it and then merge it 😊

Have a nice day,
Farha

**Comment by ofranc** [comment]
Hey @TheTwoBoom just checking if you're still interested in writing the tutorial you mentioned. If so, I'll leave the issue open, otherwise, let me know and I'll close it. Thanks!

**Comment by ofranc** [comment]
Hi @TheTwoBoom, I closed this documentation request as I haven't heard back from you in a while. We can re-open it when you're ready to contribute. Talk to you soon!
