### ISSUE TITLE
🐞 Documentation Bug: 

### ISSUE THREAD

**Issue by alter-s** [scaleway/docs-content#2073]
### What content on scaleway.com/en/docs is affected?

https://www.scaleway.com/en/developers/api/kubernetes/

### What part(s) of the content would you like to see updated?

step 3, payload is real wrong
 * ends with "`" not "'" as the -d started
 * has $SCW_REGION in project ID
 * said SCW_REGION will not be substituted due to being inside single quotes "'"

**Comment by bene2k1** [comment]
Hello @alter-s 

Thank you for opening this issue. We have fixed the typo and will deploy the fixed version of the documentation soon. 

Benedikt
