### ISSUE TITLE
👩‍💻 Documentation Request: addition to LB TLS certs handling

### ISSUE THREAD

**Issue by Timost** [scaleway/docs-content#2274]
### Summary

Following this [discussion on slack](https://scaleway-community.slack.com/archives/CEXKP0Z8X/p1697461382782589)
I think it would be worth adding a section in the documentation regarding rotating certificates (non Let'sencrypt certificates).

Maybe on this page ?
https://www.scaleway.com/en/docs/network/load-balancer/how-to/add-certificate/

### Why is it needed?

My use case is renewing paid wildcard certificates which expire once a year.
I want to do this without downtime.
This is easily doable right now but the LB behavior can be confusing.

When you add the new certificate and the old is still present on the LB, the older one will be used until it is removed.
I was expecting the new one to used.

Once the new certificate is added, one can safely remove the old one and the new one will be used.

### Want to write this documentation yourself?

No

**Comment by RoRoJ** [comment]
Hi Tim, I've just merged a modification to the documentation that should clear this up 
https://github.com/scaleway/docs-content/pull/2324

Thanks for bringing it to our attention.

**Comment by Timost** [comment]
Thank you, it makes the behaviour clearer. 👍
