### ISSUE TITLE
👩‍💻 Documentation Request: Creating a Kubernetes Cluster on Scaleway with K3s and Cilium

### ISSUE THREAD

**Issue by arthur-mrz** [scaleway/docs-content#2299]
### Summary

This tutorial provides a step-by-step guide for creating a K3S 3-nodes Kubernetes cluster on the Scaleway cloud platform. It covers the entire process, from setting up the required infrastructure, to installing and configuring K3s and Cilium. The tutorial aims for an IPv6 only setup and minimalist installation with all unnecessary features disabled.

Overview:
- Brief overview of the tutorial's purpose and scope
- Setting up Scaleway Infrastructure
- Installing K3s on the master node
- Adding nodes to the cluster
- Verifying the cluster's health
- Installation and configuration of the Cilium CNI plugin for enhanced networking and security
- Recap of the key points covered in the tutorial and encouragement for further exploration and customization

### Why is it needed?

This tutorial is essential for individuals and small businesses aiming to create a cost-effective K3s Kubernetes cluster on Scaleway with IPv6 support and minimal configuration. It caters to those seeking efficient infrastructure management and performance optimization while enhancing their understanding of Kubernetes and Cilium. This resource helps address the specific needs of budget-conscious users, IPv6 implementers, and individuals interested in secure and performant Kubernetes setups.

### Want to write this documentation yourself?

Yes

### Related PR(s)

#2326

**Comment by bene2k1** [comment]
Hello @arthur-mrz, 

Thank you for your contribution to Scaleway's Product Documentation. We have reviewed your tutorial and merged the content. It will be published on the documentation website very soon. 

We have credited your Scaleway account with €200 cloud credit that you can use for up to three months. 

Benedikt
