### ISSUE TITLE
🐞 Documentation Bug: routed flexible ips and cloud init

### ISSUE THREAD

**Issue by gustopn** [scaleway/docs-content#2372]
### What content on scaleway.com/en/docs is affected?

https://www.scaleway.com/en/docs/compute/instances/how-to/migrate-routed-ips/

### What part(s) of the content would you like to see updated?

no, it is not only that cloud-init is not compatible. Cloud init does not set ipv6 gen eui64, so either set it, or remove it altogether. I removed cloud init and set network manager up properly and now IPv6 gets correct address.
It is not enough to think it will create EUI64 out of the MAC addr, because distros have privacy extensions enabled. So either one would need to disable it generally, which is not as easy as I was thinking, because the default is always privacy extensions and even if you change that, it does not survive reboot since cloud init overwrites all network config anyway.
So the only solution is to do `dnf remove cloud\*`

### Additional context

Well, Scaleway has to choose. Either you do manual network config over cloud init, but then you need to do it statically and do not rely on SLAAC because you can never know what the end result will be. Or my preferred solution is what I done is to just remove that cloud init crap and let NetworkManager handle network configuration over DHCP, SLAAC or even DHCPv6. Because that's what it is for. Fiddling into automatic configurations with static scripts like cloud init is the worst you can do. So that was a pretty bad idea, wasn't it?

**Comment by bene2k1** [comment]
Hello, 

your feedback has been forwarded to the concerned teams, and we will come back to you as soon as possible. 

Benedikt

**Comment by gustopn** [comment]
OK
