### ISSUE TITLE
🐞 Documentation Bug: Nginx Ingress crash after applying

### ISSUE THREAD

**Issue by boomaker** [scaleway/docs-content#2478]
### What content on scaleway.com/en/docs is affected?

https://www.scaleway.com/en/docs/tutorials/k8s-kapsule-multi-az/#nginx-ingress-controller-as-a-stateless-multi-az-application

### What part(s) of the content would you like to see updated?

On this page, it is specified to create a /up route for DNS health check with the following code block in ingress-nginx chart:

```
         config:
            location-snippet: |
              location /up {
                return 200 'up';
              }
```

But this instruction will totally crash nginx if there are ingresses with path in the cluster with the following error:

```
	Error: exit status 1
	[emerg] 559#559: location "/up" is outside location "/ingress-location/" in /tmp/nginx/nginx-cfg871020442:747
	nginx: [emerg] location "/up" is outside location "/ingress-location/" in /tmp/nginx/nginx-cfg871020442:747
	nginx: configuration file /tmp/nginx/nginx-cfg871020442 test failed
```

**Comment by pablo-ruth** [comment]
Hello @boomaker,

Thanks for opening this issue. I just opened a PR to fix the issue (#2492). I removed the location-snippet that was causing the problem, and replaced it by directly using the "healthz" endpoint of the ingress controller inside the DNS healthcheck configuration.

Is it ok for you?
