### ISSUE TITLE
Security warning

### ISSUE THREAD

**Issue by samber** [scaleway/docs-content#2520]
### What content on scaleway.com/en/docs is affected?

https://github.com/samber/docs-content/blob/main/storage/object/api-cli/bucket-policy.mdx#L553C1-L574C4

### What part(s) of the content would you like to see updated?

You should not suggest customers add a "Referer: console.scaleway.com" policy statement to object storage bucket policies.

It's cool for allowing developers to access files from console.scaleway.com but it creates a huge security issue.

**Comment by SamyOubouaziz** [comment]
Hello @samber, your issue is under technical review and will be addressed shortly, thank you for raising it!

**Comment by SamyOubouaziz** [comment]
Hello again @samber, could you elaborate your statement and explain how this referer creates a security issue? Thank you in advance for your help!

**Comment by samber** [comment]
Because anybody can exec `curl -H 'Referer: https://console.scaleway.com' https://bucket.scw.com/very/private/file.xlsx` and get access to the file.

This policy is equivalent to a public bucket.

**Comment by SamyOubouaziz** [comment]
Closing this issue as the policy concerned by the security issue is specifically designed to publicly expose an object.
