### ISSUE TITLE
🐞 Documentation Bug: API Endpoints documentation is mixing singular and plural paths

### ISSUE THREAD

**Issue by LukasSkywalker** [scaleway/docs-content#2570]
### What content on scaleway.com/en/docs is affected?

https://www.scaleway.com/en/developers/api/#endpoints

### What part(s) of the content would you like to see updated?

The endpoints documentation mentions zoned and regional endpoints. The pattern (wrongly) uses the singular name `zone` as in `api.scaleway.com/{product}/{version}/zone/{zone}/{object}...`, while the example correctly uses the plural `zones` as in `api.scaleway.com/instance/v1/zones/{zone}/servers`. The same for `region` and `regions`.

![image](https://github.com/scaleway/docs-content/assets/282447/bb154496-722e-4cb8-a939-f734262c3ad4)

**Comment by RoRoJ** [comment]
Thank you for bringing this to our attention, I've opened a pull request to correct these endpoints on our repository. You should see the live page corrected by the end of the week :-)
