### ISSUE TITLE
🐞 Documentation Bug: Pulumi Resource Provider not maintained anymore - lbrlabs/pulumi-scaleway

### ISSUE THREAD

**Issue by guedressel** [scaleway/docs-content#2786]
### What content on scaleway.com/en/docs is affected?

https://www.scaleway.com/en/docs/tutorials/pulumi-quickstart/

### What part(s) of the content would you like to see updated?

The referenced Pulumi Resource Provider is no longer maintained: https://github.com/lbrlabs/pulumi-scaleway

Would be great if Scaleway Staff members could fork this project and maintain it themself officially!

**Comment by bene2k1** [comment]
Hello @guedressel,

Thank you for reaching out with your feedback on the Pulumi documentation at Scaleway. We've reviewed your concerns with our Developer Tools team, and unfortunately, we are unable to continue providing support for Pulumi at this time. However, we would like to suggest an alternative solution: [Terraform](https://www.scaleway.com/en/docs/developer-tools/terraform/quickstart/), which offers similar functionalities and robust support within our ecosystem.

For any additional questions or assistance, feel free to join our DevTools team in our [Slack community](https://slack.scaleway.com/) in #terraform. 

Benedikt
