### ISSUE TITLE
Is the resizing of an encrypted volume now allowed in Kapsule or not?

### ISSUE THREAD

**Issue by mid1221213** [scaleway/docs-content#2847]
:wave: 

https://github.com/scaleway/docs-content/blob/f068747f02b2e4843c8d6dad7938fed6ade19610/containers/kubernetes/api-cli/managing-storage.mdx#L140

The issue referenced in that note is closed as completed, and according to this [documentation](https://github.com/scaleway/scaleway-csi/blob/master/examples/kubernetes/README.md#encrypting-volumes) the resizing of an encrypted volume is now allowed.

**Comment by bene2k1** [comment]
Hello @mid1221213 👋 

Thank you for your remarks. Indeed, resizing of volumes is possible now, as described in the CSI documentation.
I have fixed the documentation, and we will update it as soon as possible (https://github.com/scaleway/docs-content/pull/2848)

Bene
