### ISSUE TITLE
🐞 Documentation Bug: IAM API example are not working

### ISSUE THREAD

**Issue by zwindler** [scaleway/docs-content#2857]
### What content on scaleway.com/en/docs is affected?

https://www.scaleway.com/en/developers/api/iam/

### What part(s) of the content would you like to see updated?

Example given to create a new policy uses organization_id in rules as an array

![image](https://github.com/scaleway/docs-content/assets/1246797/63fb8dc1-55c6-4858-87fa-30432f4ddcaf)

```
      "organization_id": [
        "c6842bac-7938-4c04-9e03-f48147eee1f1"
      ]
```

APIs calls running this example will fail, because it should be a string, not an array

![image](https://github.com/scaleway/docs-content/assets/1246797/0a4d588e-116f-4cde-b90f-ef304972acc0)

Example should be replaced by this one

```
curl -X POST \
  -H "Content-Type: application/json" \
  -H "X-Auth-Token: $SCW_SECRET_KEY" https://api.scaleway.com/iam/v1alpha1/policies \
  -d '{
  "name": "policy-prod1",
  "description": "This policy grants full access to IAM in my Organization to application prod1",
  "organization_id": "c6842bac-7938-4c04-9e03-f48147eee1f1",
  "rules": [
    {
      "permission_set_names": [
        "IAMManager"
      ],
      "organization_id": "c6842bac-7938-4c04-9e03-f48147eee1f1"
    }
  ],
  "application_id": "950dde46-5cba-427d-a4f5-ce5a8a79717c"
}'
```

### Related PR(s)

I would have opened a PR but I haven't found the related file

**Comment by ldecarvalho-doc** [comment]
Hello @zwindler, thank you!
No worries, the content of https://www.scaleway.com/en/developers/ is not open-sourced, so you would not have been able to make a PR. 
Thank you for pointing this out, I will fix the API documentation.
