### ISSUE TITLE
Add support for devcontainer

### ISSUE THREAD

**Issue by remyleone** [scaleway/docs-content#295]
https://code.visualstudio.com/docs/remote/containers

**Comment by bene2k1** [comment]
Hello @remyleone! Thanks for raising this issue a decade ago. Sorry, it took us so long to get back to you. Currently, we have no plans to add support for devcontainer on the documentation website.

Feel free to reach out to us for any further suggestions or ideas you might have to improve our product documentation.

Benedikt
