### ISSUE TITLE
👩‍💻 Documentation Request: Encode videos using Scaleway Jobs and FFMPEG

### ISSUE THREAD

**Issue by antoinechampion** [scaleway/docs-content#3090]
### Summary

- Create a Docker image that: 1) leverages FFMPEG to encode videos on demand and 2) uses Scaleway's Object Storage as a persistence layer for pulling and pushing videos.
- Push that image to Scaleway's container registry
- Deploy it as a Serverless Job
- Trigger that Job on demand

### Why is it needed?

Serverless jobs are great for audio/image/video encoding as they scale up and down as needed, saving costs by only charging for what's used. With video encoding, where demands can vary greatly, this flexibility ensures efficient processing without overspending on idle servers. It's a practical and budget-friendly solution for encoding tasks.

### Want to write this documentation yourself?

Yes

### Related PR(s)

TBA

### (Optional) Scaleway Organization ID

4993020b-9474-4a6b-bd92-f75236709147

### Email address

antoine.champion@outlook.fr

**Comment by SamyOubouaziz** [comment]
Hello @antoinechampion, thank you for this proposal! Could you confirm that you still wish to write this tutorial? If so, you can go ahead and start working on the content. 
You can refer to the [contribution guidelines](https://github.com/scaleway/docs-content/blob/main/docs/CONTRIBUTING.md) for more information on how to write documentation.
Feel free to contact us here or on the `#documentation` channel of our [Community Slack](https://slack.scaleway.com/) if you have any question.

Best,

Samy

**Comment by thomas-tacquet** [comment]
Hello @antoinechampion and thank you a lot ⭐ 

I have a question regarding your use case, do you think having GPUs on Serverless Jobs can help you for your use case ?

Thanks 👋

**Comment by antoinechampion** [comment]
@thomas-tacquet Not necessarily. I'm far from being a subject matter expert, but here's my understanding:
- GPU encoding is much faster
- CPU encoding supports a broad range of video codecs with better quality and file size

Hence GPU encoding would be more suited to real-time encoding scenarios, in which I wouldn't use a serverless job but instead a dedicated machine running 24/7.
