### ISSUE TITLE
🐞 Documentation Bug: format broken

### ISSUE THREAD

**Issue by Artem3213212** [scaleway/docs-content#3112]
### What content on scaleway.com/en/docs is affected?

https://www.scaleway.com/en/docs/labs/ipfs-pinning/api-cli/volumes-operations/#creating-a-volume

### What part(s) of the content would you like to see updated?

Format broken:
1. In https://www.scaleway.com/en/docs/labs/ipfs-pinning/api-cli/volumes-operations/#creating-a-volume
![image](https://github.com/scaleway/docs-content/assets/37815717/70baca65-c1c9-4f8f-915f-01abdda329b9)
2. In https://github.com/scaleway/docs-content/blob/main/labs/ipfs-pinning/api-cli/volumes-operations.mdx#creating-a-volume
![image](https://github.com/scaleway/docs-content/assets/37815717/6c4856fb-9ac8-40f0-8be9-88ce49f771e7)

**Comment by Artem3213212** [comment]
Same in https://www.scaleway.com/en/docs/labs/ipfs-pinning/api-cli/getting-started-with-ipfs-cli/

**Comment by bene2k1** [comment]
Hello @Artem3213212,

Thank you for bringing the pages with broken formatting to our attention. I've made the necessary updates and created a merge request (#3138). We'll merge it as soon as possible.

If you have any further questions or concerns, don't hesitate to reach out to us.

Benedikt
