### ISSUE TITLE
🐞 Documentation Bug: died lib in examples

### ISSUE THREAD

**Issue by Artem3213212** [scaleway/docs-content#3121]
### What content on scaleway.com/en/docs is affected?

https://www.scaleway.com/en/docs/labs/ipfs-pinning/api-cli/ipfs-get-content/

### What part(s) of the content would you like to see updated?

In section [Retrieving content using a Go client](https://www.scaleway.com/en/docs/labs/ipfs-pinning/api-cli/ipfs-get-content/#retrieving-content-using-a-go-client) code example use died lib (`github.com/ipfs-pinning/go-ipfs-pinning-api`).

**Comment by ldecarvalho-doc** [comment]
Hello @Artem3213212!
Thank you for your feedback. @OnsagerHe created a PR to fix the issue. I hope it works well now.
We will merge this content within the day. 
Have a nice day!
