### ISSUE TITLE
[👩‍💻 Documentation Request]: How to use Glacier storage for backups?

### ISSUE THREAD

**Issue by RaindropsSys** [scaleway/docs-content#3122]
### Summary

I found documentation about object storage and more specifically using Glacier storage to be very sparse and spread across multiple pages. A guide would be laid out similar to this:

- Short introduction to object storage and Glacier
- Creating a bucket like is mentioned [here](https://www.scaleway.com/en/docs/storage/object/quickstart/#how-to-upload-files-into-a-bucket)
- Installing the AWS-CLI and configuring it for object storage like mentioned [here](https://www.scaleway.com/en/docs/storage/object/api-cli/object-storage-aws-cli/)
- Using the AWS-CLI to upload files to the bucket directly into the Glacier storage class (that was the most frustrating part, as I did not find any Scaleway-specific documentation for this).

### Why is it needed?

I found it very frustrating to not find any proper guide when trying to just use object storage for backups. As a newbie in object storage, I feel a certain lack in documentation related to using object storage.

### Want to write this documentation yourself?

No

### (Optional) Scaleway Organization ID

aa9bfa7f-bfb2-43a1-b07c-1c2a116dd27d

**Comment by RaindropsSys** [comment]
Note: While I mentioned I do not want to, I can write this documentation myself if needed (and rewarded appropriately).

**Comment by SamyOubouaziz** [comment]
Hello @RaindropsSys, thank you for your feedback. As Scaleway Object Storage relies on the S3 protocol, we do not provide dedicated Scaleway tools besides the Console. However, you can use a large variety of popular S3 tools such as the [AWS CLI](https://www.scaleway.com/en/docs/storage/object/api-cli/object-storage-aws-cli/), the [MinIO client ](https://www.scaleway.com/en/docs/storage/object/api-cli/installing-minio-client/)or any S3-compatible SDK (such as Boto3). You can refer to the official documentation of these tools for more information on how to work with Glacier.

There is indeed a lack of centralized documentation regarding Glacier, we will review the existing documentation quickly and fill the caveats accordingly.

Hope this helps, thanks again for sharing your feedback!

Best,

Samy
