### ISSUE TITLE
👩‍💻 Documentation Request: 

### ISSUE THREAD

**Issue by thomasbeaujean** [scaleway/docs-content#3449]
### Summary

Troubleshooting http 400 error in Kubernetes Network.

### Why is it needed?

When you create a fresh Kubernetes  and add an Ingress Nginx using EasyDeploy, and enable proxy, then it does not work.

The LB is using TCP and the Nginx does not accept TCP by default.

### Want to write this documentation yourself?

Yes

### Related PR(s)

https://github.com/scaleway/docs-content/pull/3448

### Email address

thomas.beaujean@dayploy.fr

**Comment by bene2k1** [comment]
Hello @thomasbeaujean,

Thank you for your contribution to Scaleway's Product Documentation.
Your PR has been merged, and your modifications have been published. 

Benedikt
