### ISSUE TITLE
Add some information about exposing power usage figures in Elastic Metal

### ISSUE THREAD

**Issue by mrchrisadams** [scaleway/docs-content#345]
Hi there.

Would you consider adding some information to the docs for your new elastic-metal product about what info is provided in terms of power usage used by a server?

Below are the docs I'm referring to:
https://www.scaleway.com/en/docs/faq/elastic-metal/

And I'm asking in the context of using something like Scaphandre on it, to allow me to report, as a customer for location based carbon the emissions used by my compute:
https://github.com/hubblo-org/scaphandre

For this to be possible, I think the processors need to expose information recorded by the RAPL sensor as documented here:

https://hubblo-org.github.io/scaphandre-documentation/explanations/how-scaph-computes-per-process-power-consumption.html

BTW, I'm aware of Scaleway's environmental leadership page below, and I'm a customer because of it, but I know that when I am running workloads in Poland or the Netherlands, there will be location based carbon emissions I'd like to track.
https://www.scaleway.com/en/environmental-leadership/

Thanks!

**Comment by bene2k1** [comment]
Hi @mrchrisadams,

Thank you for contacting us about the PUE of our Elastic Metal offers. Unfortunately, this information cannot be shared publicly at the moment. However, we are working on providing detailed information on the energy consumption of our services in the future. In the meantime rest assured that all our Elastic Metal offers are designed with their power usage in mind and all servers are deployed in our DC5 datacenter, which provides one of the lowest PUE and water usage ratios in the market. 

Do not hesitate to contact our support team with any additional questions regarding our Elastic Metal offers you may have. My colleagues will be happy to assist you. 

Regards,

Benedikt
