### ISSUE TITLE
VPC and Public Gateway troubleshooting section update

### ISSUE THREAD

**Issue by Timost** [scaleway/docs-content#362]
Hi,

I've been having trouble getting a fresh VPC + Public Gateway + Instance (lUbuntu Focal image provided by scaleway) + ssh NAT rule working (same issue as https://www.scaleway.com/en/docs/network/vpc/troubleshooting/cant-connect-to-instance-with-pn-gateway).

After a few experiments, it turns out I need to `apt update && apt upgrade` and then `reboot` once before the instance properly joins the VPC with DHCP working.
Therefore it feels like VPC and public gateway is kind of broken out of the box right now.

As far as I can tell this is not specifically documented in the troubleshooting section or elsewhere in the documentation.
I think, it should be fixed or at the very least clearly documented somewhere.

If you accept PRs, I can submit a change to the troubleshooting section.

**Comment by ofranc** [comment]
Hello @Timost ! Thank you for raising the issue. You were right, you needed to `apt update && apt upgrade` and then `reboot` your Instance to make it work properly. Since your comment, the issue is being fixed (as we speak) and the updated image should be available really soon. Thanks again.

**Comment by Timost** [comment]
Hi @ofranc !
Thank you for the update, Is there a way for me to know when the updated images will be available ? Something I can subscribe to for example ?

Linking with https://github.com/scaleway/terraform-provider-scaleway/issues/1059 in case people stumble on the same issue as I am.

**Comment by ofranc** [comment]
Hey @Timost, the new images should be available now. You can check out our [changelog](https://www.scaleway.com/en/changelog/?date=12-2021) to stay tuned on the latest releases of our products.

**Comment by Timost** [comment]
Alright ! Thanks !
