### ISSUE TITLE
Database: High-Availability configuration

### ISSUE THREAD

**Issue by amit-tewari** [scaleway/docs-content#564]
https://blog.scaleway.com/dbaas-behind-the-scenes/?_ga=2.165204476.21152594.1650533932-106614129.1650533932 does a great job explaining how it works.
One information point shall make it more useful: Are standby/ replica hosted in same data center where primary/ master is hosted?
May you please add this in FAQ for Databases please?

**Comment by bene2k1** [comment]
Hello @amit-tewari ,

Thank you for your feedback about the Scaleway Product Documentation. Regarding your question about having nodes in different datacenters, I can tell you that in a high-availablity cluster, active and hot standby nodes are indeed located in the same datacenter but in two separated racks. The idea is to offer the best performances to our users by reducing latencies between active and hot standby nodes as we use a sync replication process between the nodes.

We will add this question to our FAQ to provide this information to our users.
