### ISSUE TITLE
👩‍💻 Documentation Request: Documentation for (traefik) ingress controller for kapsule without using UI

### ISSUE THREAD

**Issue by mkarbo** [scaleway/docs-content#572]
### Summary

Add documentation on how to setup kapsule cluster with ingress in Terraform (or in a way that can be automated).

Currently, documentation and blogs mostly reference the UI deployment process, and for people who are 'new' to scaleway (and maybe ingress), it would be a huge help to have either:
- Terraform provider extended documentation
- Blog post documentation (like [this excellent page](https://www.scaleway.com/en/docs/tutorials/traefik-v2-cert-manager/) but for automated setup)

### Why is it needed?

Most current documentation relies on setting up ingress controller via UI. However, even CLI and API documentation appears to be outphasing the managed ingress controllers.

Currently, terraform provider documentation for scaleway clusters only provide an example for nginx-ingress controller 
- see e.g., [terraform provider documentation](https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/resources/k8s_cluster)

It would be lovely to have an up to date snippet for provisioning kapsule clusters with terraform and adding traefik(2) ingress controller.

### Want to write this documentation yourself?

No

**Comment by bene2k1** [comment]
Hello,

Thank you for your interest in the Scaleway Product Documentation and the suggestion you made. We have evaluated your request with the technical teams and we can inform you that the deployment of an ingress controller is deprecated and this feature will be removed from the Kubernetes Kapsule product. You can deploy your applications using the easy deploy feature now. For more information, we invite you to read our documentation about the easy deploy feature: 
https://www.scaleway.com/en/docs/compute/kubernetes/how-to/enable-easy-deploy
