### ISSUE TITLE
🐞 Documentation Bug: Scaleway Instance is inaccessible from new SSH Key added

### ISSUE THREAD

**Issue by codezart** [scaleway/docs-content#602]
### Summary

Added a new SSH key to the project.
Tried accessing an already created instance using the new SSH key, but it doesn't work.
Tried accessing with SSH keys that were added before that instance was created and that worked.

Upon looking at the documentation: https://www.scaleway.com/en/docs/console/my-project/how-to/create-ssh-key/#how-to-upload-the-public-ssh-key-to-the-scaleway-interface

it mentions that I use 

`scw-fetch-ssh-keys --upgrade`

This command does not work with scaleway cli

It seems this needs to be updated

### Why is it needed?

It is needed because the old documentation does not work.

### Want to write this documentation yourself?

No

**Comment by RoRoJ** [comment]
Hi @codezart 

Thank you for raising this issue. In fact, the command `scw-fetch-ssh-keys --upgrade` is not a CLI command, but rather a command you can run once connected to your Instance, which launches a script to update your Instance with any new SSH keys that have been added to your Project.

I am updating our doc to clarify this, please see the PR in review: https://github.com/scaleway/docs-content/pull/610 . Feel free to add any suggestions!

I've tested this solution myself for updating an Instance with a new SSH key and it worked well for me. If you are still having problems connecting to your Instance, I suggest [opening a support ticket](https://www.scaleway.com/en/docs/console/my-account/how-to/open-a-support-ticket/)

Best wishes,
Rowena (Product Documentation team)
