### ISSUE TITLE
👩‍💻 Documentation Request: Add minimum node_type for pools 

### ISSUE THREAD

**Issue by aichbauer** [scaleway/docs-content#745]
### Summary

Currently, there is no information on which instance types you can use in your pool (according to the docs and to the support team).

I would like to add some information on that by changing this

`A pool is a set of identical Nodes. A pool has a name, a size (its current number of nodes), nodes number limits (min and max), and a Scaleway Instance type. Changing these limits increases/decreases the size of a pool. Thus, when autoscaling is enabled, the pool will grow or shrink inside those limits, depending on its load.` 

To

`A pool is a set of identical Nodes. A pool has a name, a size (its current number of nodes), nodes number limits (min and max), and a Scaleway Instance type (minimum DEV1-M). Changing these limits increases/decreases the size of a pool. Thus, when autoscaling is enabled, the pool will grow or shrink inside those limits, depending on its load.` 

### Why is it needed?

We migrate our infrastructure to a European cloud provider. While setting up testing infrastructures with terraform, I was getting error messages: `scaleway-sdk-go: invalid argument(s): node_type does not respect constraint, this node type is not available in this zone`

This led me to investigate for which node types are available in which zone. After some time, we (the support team and I) found out that it has nothing to do with the zone (so probably we want to replace this error message as well), but with the node_type itself. You can only use DEV1-M and higher in your pool.

### Want to write this documentation yourself?

Yes

### Scaleway Organization ID

09e5de46-6743-41e4-985f-6d06176c9ae8

### Email address

l.aichbauer@gmail.com

**Comment by bene2k1** [comment]
Hello @aichbauer,

Thank you for your feedback. Indeed the minimum Instance type to use with Kubernetes is DEV1-M. 
DEV1-S Instances have RAM constraints which make them unsuitable for use in Kubernetes clusters. We have updated our documentation to make this clear:

https://www.scaleway.com/en/docs/compute/kubernetes/api-cli/creating-managing-kubernetes-lifecycle-cliv2/#adding-a-pool-to-a-k8s-cluster

Don't hesitate to reach out to us again if you have any further suggestions or feedback on how to improve our documentation. 

Benedikt
