### ISSUE TITLE
🐞 Documentation Bug: 

### ISSUE THREAD

**Issue by Talispaehn** [scaleway/docs-content#746]
### What content on scaleway.com/en/docs is affected?

https://www.scaleway.com/en/docs/tutorials/openvpn-instant-app/

### What part(s) of the content would you like to see updated?

Point 3 of intro references nextcloud ("Choose the NextCloud image in the InstantApps tab")

This has nothing to do with nextcloud.

It should reference openvpn.

**Comment by bene2k1** [comment]
Hell @Talispaehn, 

Thank you for your contribution to Scaleway's documentation. 
I have fixed the bug in the tutorial. 

Don't hesitate to reach out to us for any further suggestions or ideas regarding our product documentation you might have. 

Benedikt
