### ISSUE TITLE
👩‍💻 Documentation Request: Add documentation on Load-Balancer sticky sessions modes

### ISSUE THREAD

**Issue by Timost** [scaleway/docs-content#754]
### Summary

Sticky sessions on load-balancers are under documented, there are two modes of stickiness: table and cookie based.

I think those modes should be documented.
The current doc does not mention them as far as I can tell.

The file is here I think
https://github.com/scaleway/docs-content/blob/main/network/load-balancer/concepts.mdx#sticky-session

### Why is it needed?

To be able to make an informed decision on what mode to use.

### Want to write this documentation yourself?

No

**Comment by RoRoJ** [comment]
Thanks for this suggestion, we've enriched our documentation on sticky sessions!
See this PR: 
https://github.com/scaleway/docs-content/pull/763

Don't hesitate to let us know if there's anything else you feel is missing from the doc site in the future.
