### ISSUE TITLE
🐞 Documentation Bug: no mention of hard cap of 1 baremetal m1 server per org

### ISSUE THREAD

**Issue by craigsc** [scaleway/docs-content#774]
### What content on scaleway.com/en/docs is affected?

https://www.scaleway.com/en/docs/compute/apple-silicon/quickstart/?_ga=2.151592890.205576053.1659992781-1354343814.1659992781

### What part(s) of the content would you like to see updated?

There's zero mention that there is a hard cap of 1 bare metal M1 allowed per org. We just hit this after starting to use your services and hoping to scale out our usage to a few machines and it took a manual chat with customer service for us to learn it which left a super bad taste in our mouths as a new customer. This feels like it should be very clearly marked on your docs near the 24hour leasing limit.

**Comment by nedaehm** [comment]
Hi @craigsc, thank you for reporting this bug issue. We have updated our [documentation](https://www.scaleway.com/en/docs/compute/apple-silicon/quickstart/#how-to-create-a-mac-mini-m1)! Feel free to contribute again 😄 
Have a nice day!
