### ISSUE TITLE
🐞 Documentation Bug: List elements does not render appropriately 

### ISSUE THREAD

**Issue by sbres** [scaleway/docs-content#808]
### What content on scaleway.com/en/docs is affected?

https://www.scaleway.com/en/docs/compute/containers/how-to/add-a-custom-domain-to-a-container/

### What part(s) of the content would you like to see updated?

Hello,

There is a list of steps to follow to be able to get the custom domain to a container.
When looking at the scaleway website the numbering of steps are 1 1 2 
This makes the documentation confusing as I was interpreting this documentation as two different ways of doing things.
From the documentaion on github the numbering is correct.
https://github.com/scaleway/docs-content/blob/main/compute/containers/how-to/add-a-custom-domain-to-a-container.mdx

**Comment by bene2k1** [comment]
Hi @sbres,

Thank you for spotting this. I am going to fix the issue and will let you know once it is fixed. 

Benedikt

**Comment by bene2k1** [comment]
Hi, 

I have fixed the issue and updated the documentation. 

Don't hesitate to open another issue if there is anything we can improve :) 

Benedikt
