### ISSUE TITLE
[👩‍💻 Documentation Request]: Apache with Let's Encrypt TLS certificate(s) managed using mod_md

### ISSUE THREAD

**Issue by vedranmiletic** [scaleway/docs-content#828]
### Summary

How to set up Apache with Let's Encrypt TLS certificate(s) managed using mod_md. In addition, the guide will also describe how to configure Apache for presently used TLS standards (1.2 and 1.3).

### Why is it needed?

Unlike Certbot, this approach is built-in into Apache and doesn't require manually setting up a systemd timer that stops the web server and restarts it later so Certbot can renew certificates.

### Want to write this documentation yourself?

Yes

### Related PR(s)

n/a

### Scaleway Organization ID

54fc9dcf-a8af-4ac8-90a4-b8a44e722162

### Email address

vedran@miletic.net

**Comment by RoRoJ** [comment]
Hi [vedranmiletic](https://github.com/vedranmiletic), thanks for opening this Issue.

We are happy to approve your request - you can contribute to our doc with your tutorial, and have a discount of up to €200 applied to your account.

Just remember that the tutorial needs to be for one or more specific Scaleway products (probably Instance?).

For more information, refer to our [contribution page](https://www.scaleway.com/en/docs/contribute/).

Go ahead and open a PR when you’re ready!

**Comment by ofranc** [comment]
Hello @vedranmiletic, I'll close your issue for now. Do not hesitate to open a PR when you're ready :)
