### ISSUE TITLE
👩‍💻 Documentation Request: Please include API

### ISSUE THREAD

**Issue by masaoliou** [scaleway/docs-content#905]
### Summary

Where is the good old RESTful API?

The [present document](https://www.scaleway.com/en/docs/compute/instances/api-cli/creating-managing-instances-with-cliv2/) says: "You can create and manage your Instances from the console, via the API or via the Scaleway Command Line Interface."

But I am unable to find the documentation for API.

### Why is it needed?

I need to _automate_ such operations as below:

- Create new instances.
- Drop existing instances.
- Migrate instances.

### Want to write this documentation yourself?

No

**Comment by bene2k1** [comment]
Hello @masaoliou, 

You can find the API documentation for all our products at the following link: https://developers.scaleway.com/en/

I will add the link to the documentation you mentioned above. 

Benedikt

**Comment by bene2k1** [comment]
https://github.com/scaleway/docs-content/pull/906

**Comment by masaoliou** [comment]
Thank you.

Please do not forget to add back the [lost links](https://www.scaleway.com/en/docs/faq/blockstorage/) in red color.
