### ISSUE TITLE
👩‍💻 Documentation Request: How to provide your own Certificate Authority

### ISSUE THREAD

**Issue by fabien-ch** [scaleway/docs-content#956]
### Summary

I try to create my own Certificate Authority but all what i tried doesn't work. I try to follow the documentation https://www.scaleway.com/en/docs/iot/iot-hub/how-to/provide-own-certificate-authority/ but it's not enough

### Why is it needed?

More explanation on how to generate own Certificate Authority

### Want to write this documentation yourself?

No

**Comment by bene2k1** [comment]
Hello @fabien-ch,

You can follow one of the tutorials available to generate your own certificate authority, for example: https://priyalwalpita.medium.com/create-your-own-certificate-authority-47f49d0ba086 - However, keep in mind that certificates signed by your own CA are not recognised by web browsers and may cause displaying a warning.
Using a certificate issued by a trusted CA whenever possible is recommended. For example, using Let's Encrypt. 

Benedikt
